export {
  getDb, hasDb, migrate, closeDb,
  dbQueryAll, dbQueryFirst, dbExecute, dbExecRaw,
  saveAnalysisRecord, getAnalysisRecords, getAnalysisRecordById,
  savePortfolioRecord, getPortfolioRecords, getPortfolioRecordsByGuest, deletePortfolioRecord, updatePortfolioRecord,
  updatePortfolioSyncedPrice, listPortfolioRecordsForSync,
  saveTradeJournalEntry, listTradeJournalEntries, getTradeJournalEntryById,
  updateTradeJournalEntry, deleteTradeJournalEntry,
  saveClaimCode, findGuestByClaimCode, reassignGuestRecords,
  getHistoricalGifts, ensureSeedData,
  logPlacementEvent, getPlacementEventStats,
  getUserById, getUserIdentities, findOrCreateUser, getUsageCount, consumeAnalysisQuota, refundAnalysisQuota,
  getRecognitionUsage, consumeRecognitionQuota, refundRecognitionQuota,
  searchStocksByName, fuzzySearchStocksByName, damerauLevenshtein,
  deleteAnalysisRecord,
  saveMarketFocus, getMarketFocus, saveMarketFocusMeta, getMarketFocusMeta,
  saveMarketFocusWind, getMarketFocusWind,
  logMarketFocusEvent, getLatestMarketFocusLog, listMarketFocusLogs, cleanupMarketFocusLogs,
  cleanupSocialCardImages,
  saveCycleEntrySignals, getCycleEntrySignalsByEdition,
  saveCycleEntryMeta, getLatestCycleEntryMeta, getCycleEntryMetaByEdition,
  listCycleEntryEditions, countCycleEntrySignals,
  ARENA_MAX_AGENTS_PER_USER,
  saveArenaSeason, getArenaSeasonById, getActiveArenaSeason, ensureActiveArenaSeason, ensureSystemArenaAgents, listArenaSeasons, updateArenaSeasonStatus,
  createArenaAgent, getActiveArenaAgentByOwner, countArenaAgentsByOwner,
  getArenaAgentById, listActiveArenaAgents, listArenaAgentsBySeason,
  updateArenaAgentConfig, setArenaAgentStatus, updateArenaAgentLastRound, updateArenaAgentCash,
  getArenaHoldings, replaceArenaHoldings, insertArenaTrade, getArenaTrades,
  upsertArenaSnapshot, getArenaSnapshots, getArenaLeaderboard, resetArenaAgentLedger,
  saveArenaIntradayPrices, getArenaIntradayPrices,
  saveArenaMarketBriefing, getArenaMarketBriefing,
  getArenaRoundProgress, listArenaRoundProgress, markArenaRoundProgress, clearArenaRoundProgress,
  replaceArenaRoundUniverse, getArenaRoundUniverse, clearArenaPhaseArtifacts,
  getArenaTradesByRound, getArenaTradesAllByRound,
  insertArenaDecisionLog, getArenaDecisionLogs, getArenaRoundDecisionLogs,
  saveArenaDiscussion, getArenaDiscussion, listArenaRoundDates,
  hasSocialPosted, countSocialPublishedPosts, createSocialPost, updateSocialPost, listSocialPosts, deleteSocialPostByEdition, getSocialPost,
  saveSocialCardImage, getSocialCardImage,
  getAgentSetting, setAgentSetting, listAgentSettings,
  getUserUsageReport,
  subscribeMarketFocus, confirmMarketFocusSubscription, unsubscribeMarketFocusByToken, setMarketFocusSubscriberStatus,
  deleteMarketFocusSubscriber, listMarketFocusSubscribers, listActiveMarketFocusSubscribers,
  countMarketFocusSubscribers,
  logLlmUsage,
  getLlmUsageReport,
  getLlmUsageDailyReport,
  getLlmUsageMinuteReport,
  groupLlmUsageByDay,
  groupLlmUsageByMinute,
  taipeiDayOf,
  taipeiMinuteOf,
  toTaipeiParts,
  taipeiTodayStr,
  LLM_OTPM_LIMIT,
  LLM_OTPM_ALERT_THRESHOLD,
  LLM_USAGE_DAILY_MAX_DAYS,
  LLM_USAGE_ROW_LIMIT,
  saveAnalysisJob, updateAnalysisJob, getAnalysisJobById, listAnalysisJobsByUser,
  saveArenaTickJob, updateArenaTickJob, getArenaTickJobById, findRunningArenaTickJob, cleanupArenaTickJobs,
  upsertTwseDividends, getTwseDividendsByYear, hasTwseDividendsForDate, getTwseDividendsInWindow,
  normalizeArenaDividendSymbol, saveArenaDividendCredit, hasArenaDividendCredit, getArenaDividendCredits,
} from './db.js'
export type { AnalysisRecord, AnalysisJobRow, AnalysisJobInput, AnalysisJobUpdate, AnalysisJobAgentState, AnalysisJobStatus, PortfolioRecord, PortfolioRecordInput, PortfolioRecordUpdate, PortfolioSyncedPricePatch, PortfolioSyncTarget, TradeJournalEntry, TradeJournalInput, TradeJournalDirection, TradeJournalUpdate, HistoricalGift, UserRow, UserIdentityRow, AuthProvider, IdentityInput, QuotaResult, MarketFocusItem, MarketFocusMeta, MarketFocusWind, MarketFocusWindDirection, MarketFocusLogRow, MarketFocusLogInput,
  ArenaSeasonRow, ArenaAgentRow, ArenaHoldingRow, ArenaTradeRow, ArenaSnapshotRow, ArenaAgentInput, ArenaLeaderboardRow,
  ArenaIntradayPriceRow, ArenaMarketBriefingRow, ArenaDecisionLogRow, ArenaDiscussionRow,
  SocialPostRow, SocialPostInput, SocialPostPlatform, SocialPostStatus,
  AgentSettingRow, UserUsageReportRow,
  MarketFocusSubscriberRow, MarketFocusSubscriberStatus,
  CycleEntrySignalRow, CycleEntryMetaRow,
  LlmUsageLogInput, LlmUsageAgentReport, LlmUsageReportResult,
  LlmUsageRawRow, LlmUsageDailyAgentRow, LlmUsageDailyDay, LlmUsageDailyResult,
  LlmUsageMinuteBucket, LlmUsageMinuteResult,   ArenaTickJobRow, ArenaTickJobInput, ArenaTickJobUpdate,
  TwseDividendRow, TwseDividendInput, ArenaDividendCreditRow, ArenaDividendCreditInput } from './db.js'
export { exportSyncData, mergeExports, applySyncMerge, applySyncImport, SYNC_TABLES } from './sync.js'
export type { SyncExport, SyncRow, MergedExport, SyncTableName, TaggedRow, RowSource } from './sync.js'
export type { Database } from 'better-sqlite3'
export { fetchTwseOddLots } from './fetchers/twse-odd-lot.js'
export { fetchStockGift, fetchStockGiftRows } from './fetchers/stock-gift.js'
export type { GiftRow } from './fetchers/stock-gift.js'
export {
  fetchMopsMeetings,
  fetchMopsAnnouncementText,
  classifyClaimRule,
  rocToMonthDay,
  extractGiftEvidence,
} from './fetchers/mops.js'
export type { MopsMeeting, ClaimRule, ClaimResult } from './fetchers/mops.js'
export { fetchTwseMeetings } from './fetchers/twse-meetings.js'
export type { TwseMeeting } from './fetchers/twse-meetings.js'

