/**
 * 台股大型股清單（TWSE 上市），作為週期進場掃描的候選宇宙。
 * 以 symbol（Yahoo 格式 "XXXX.TW"）為主鍵；name 為中文俗名，
 * 僅在 Yahoo 回傳短名缺失時作為顯示兜底。
 */
export interface UniverseEntry {
  symbol: string
  name: string
}

export const TW_LARGE_CAP_UNIVERSE: UniverseEntry[] = [
  { symbol: '1101.TW', name: '台泥' },
  { symbol: '1102.TW', name: '亞泥' },
  { symbol: '1216.TW', name: '統一' },
  { symbol: '1301.TW', name: '台塑' },
  { symbol: '1303.TW', name: '南亞' },
  { symbol: '1326.TW', name: '台化' },
  { symbol: '1402.TW', name: '遠東新' },
  { symbol: '1504.TW', name: '東元' },
  { symbol: '1513.TW', name: '中興電' },
  { symbol: '1717.TW', name: '長興' },
  { symbol: '1802.TW', name: '台玻' },
  { symbol: '2002.TW', name: '中鋼' },
  { symbol: '2105.TW', name: '正新' },
  { symbol: '2207.TW', name: '和泰車' },
  { symbol: '2301.TW', name: '光寶科' },
  { symbol: '2303.TW', name: '聯電' },
  { symbol: '2308.TW', name: '台達電' },
  { symbol: '2311.TW', name: '日月光' },
  { symbol: '2317.TW', name: '鴻海' },
  { symbol: '2324.TW', name: '仁寶' },
  { symbol: '2327.TW', name: '國巨' },
  { symbol: '2330.TW', name: '台積電' },
  { symbol: '2344.TW', name: '華邦電' },
  { symbol: '2347.TW', name: '聯強' },
  { symbol: '2353.TW', name: '宏碁' },
  { symbol: '2356.TW', name: '英業達' },
  { symbol: '2357.TW', name: '華碩' },
  { symbol: '2368.TW', name: '金像電' },
  { symbol: '2376.TW', name: '技嘉' },
  { symbol: '2377.TW', name: '微星' },
  { symbol: '2379.TW', name: '瑞昱' },
  { symbol: '2382.TW', name: '廣達' },
  { symbol: '2388.TW', name: '威盛' },
  { symbol: '2395.TW', name: '研華' },
  { symbol: '2408.TW', name: '南亞科' },
  { symbol: '2412.TW', name: '中華電' },
  { symbol: '2449.TW', name: '京元電子' },
  { symbol: '2454.TW', name: '聯發科' },
  { symbol: '2498.TW', name: '宏達電' },
  { symbol: '2542.TW', name: '興富發' },
  { symbol: '2603.TW', name: '長榮' },
  { symbol: '2606.TW', name: '裕民' },
  { symbol: '2609.TW', name: '陽明' },
  { symbol: '2610.TW', name: '華航' },
  { symbol: '2611.TW', name: '志信' },
  { symbol: '2615.TW', name: '萬海' },
  { symbol: '2618.TW', name: '長榮航' },
  { symbol: '2634.TW', name: '漢翔' },
  { symbol: '2801.TW', name: '彰銀' },
  { symbol: '2812.TW', name: '台中銀' },
  { symbol: '2823.TW', name: '中壽' },
  { symbol: '2834.TW', name: '台企銀' },
  { symbol: '2880.TW', name: '華南金' },
  { symbol: '2881.TW', name: '富邦金' },
  { symbol: '2882.TW', name: '國泰金' },
  { symbol: '2883.TW', name: '開發金' },
  { symbol: '2884.TW', name: '玉山金' },
  { symbol: '2885.TW', name: '元大金' },
  { symbol: '2886.TW', name: '兆豐金' },
  { symbol: '2887.TW', name: '台新金' },
  { symbol: '2888.TW', name: '新光金' },
  { symbol: '2890.TW', name: '永豐金' },
  { symbol: '2891.TW', name: '中信金' },
  { symbol: '2892.TW', name: '第一金' },
  { symbol: '2897.TW', name: '王道銀行' },
  { symbol: '2912.TW', name: '統一超' },
  { symbol: '3008.TW', name: '大立光' },
  { symbol: '3017.TW', name: '奇鋐' },
  { symbol: '3023.TW', name: '信邦' },
  { symbol: '3034.TW', name: '聯詠' },
  { symbol: '3037.TW', name: '欣興' },
  { symbol: '3044.TW', name: '健鼎' },
  { symbol: '3045.TW', name: '台灣大' },
  { symbol: '3231.TW', name: '緯創' },
  { symbol: '3264.TW', name: '欣銓' },
  { symbol: '3443.TW', name: '創意' },
  { symbol: '3481.TW', name: '群創' },
  { symbol: '3533.TW', name: '嘉澤' },
  { symbol: '3596.TW', name: '智易' },
  { symbol: '3653.TW', name: '健策' },
  { symbol: '3661.TW', name: '世芯-KY' },
  { symbol: '3680.TW', name: '家登' },
  { symbol: '3702.TW', name: '大聯大' },
  { symbol: '3711.TW', name: '日月光投控' },
  { symbol: '4938.TW', name: '和碩' },
  { symbol: '4958.TW', name: '臻鼎-KY' },
  { symbol: '5269.TW', name: '祥碩' },
  { symbol: '5388.TW', name: '中磊' },
  { symbol: '5483.TW', name: '中美晶' },
  { symbol: '5876.TW', name: '上海商銀' },
  { symbol: '5880.TW', name: '合庫金' },
  { symbol: '6005.TW', name: '群益證' },
  { symbol: '6116.TW', name: '彩晶' },
  { symbol: '6176.TW', name: '瑞儀' },
  { symbol: '6239.TW', name: '力成' },
  { symbol: '6271.TW', name: '同欣電' },
  { symbol: '6409.TW', name: '旭隼' },
  { symbol: '6415.TW', name: '矽力-KY' },
  { symbol: '6488.TW', name: '環球晶' },
  { symbol: '6505.TW', name: '台塑化' },
  { symbol: '6515.TW', name: '穎崴' },
  { symbol: '6531.TW', name: '愛普' },
  { symbol: '6669.TW', name: '緯穎' },
  { symbol: '6770.TW', name: '力積電' },
  { symbol: '6790.TW', name: '采鈺' },
  { symbol: '8069.TW', name: '元太' },
  { symbol: '8210.TW', name: '勤誠' },
  { symbol: '9904.TW', name: '寶成' },
  { symbol: '9910.TW', name: '豐泰' },
  { symbol: '9917.TW', name: '中保科' },
  { symbol: '9921.TW', name: '巨大' },
  { symbol: '9945.TW', name: '潤泰新' },
]

/** 依 symbol 索引（用於去重與查名）。 */
export const TW_LARGE_CAP_UNIVERSE_BY_SYMBOL: Map<string, string> = new Map(
  TW_LARGE_CAP_UNIVERSE.map((u) => [u.symbol, u.name]),
)